### ISSUE TITLE
Unable to install utils3d

### ISSUE THREAD

**Issue by acolasialiuliu** [IgorAherne/trellis-stable-projectorz#25]
I tried to install manually, pip list shows installation success, but the automatic program still gives the following error：

Executing pip install command: "F:\work\AI\trellis-spz\code\venv\Scripts\python.exe" -m pip install --no-cache-dir --isolated  "git+https://github.com/EasternJournalist/utils3d.git@9a4eb15e4021b67b12c460c7057d642626897ec8" --verbose
Using pip 24.3.1 from F:\work\AI\trellis-spz\code\venv\Lib\site-packages\pip (python 3.11)
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting git+https://github.com/EasternJournalist/utils3d.git@9a4eb15e4021b67b12c460c7057d642626897ec8
  Cloning https://github.com/EasternJournalist/utils3d.git (to revision 9a4eb15e4021b67b12c460c7057d642626897ec8) to f:\缓存\temp\pip-req-build-uznjxzpm

Command failed (attempt 1/3):
Error output:
  Running command git version
  git version 2.47.1.windows.1
  Running command git clone --filter=blob:none https://github.com/EasternJournalist/utils3d.git 'F:\缓存\temp\pip-req-build-uznjxzpm'
  Cloning into 'F:\缂撳瓨\temp\pip-req-build-uznjxzpm'...
  fatal: unable to access 'https://hub.fastgit.org/EasternJournalist/utils3d.git/': Failed to connect to hub.fastgit.org port 443 after 21317 ms: Could not connect to server
  error: subprocess-exited-with-error

  git clone --filter=blob:none https://github.com/EasternJournalist/utils3d.git 'F:\缓存\temp\pip-req-build-uznjxzpm' did not run successfully.
  exit code: 128

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: git clone --filter=blob:none https://github.com/EasternJournalist/utils3d.git 'F:\缓存\temp\pip-req-build-uznjxzpm'
  cwd: [inherit]
error: subprocess-exited-with-error

git clone --filter=blob:none https://github.com/EasternJournalist/utils3d.git 'F:\缓存\temp\pip-req-build-uznjxzpm' did not run successfully.
exit code: 128

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Waiting 5 seconds before retry...

setting the path to the ca_bundle: F:\work\AI\trellis-spz\code\..\tools\git\mingw64\etc\ssl\certs\ca-bundle.crt   path exists: True

**Comment by acolasialiuliu** [comment]
感谢 #24 的回答，由于我可以手动clone该项目，正好看到了install.py中相关地址，我便修改了他
文件第230行修改为
pip install "git+https://gitclone.com/github.com/EasternJournalist/utils3d.git"', 'Installing utils3d

**Comment by IgorAherne** [comment]
@acolasialiuliu This was resolved in here https://github.com/IgorAherne/trellis-stable-projectorz/issues/24#issuecomment-2593845555

**Comment by acolasialiuliu** [comment]
不太一致，我的最终还是网络问题，项目不识别我手动安装的utils3d。最后我修改了默认clone地址

> @acolasialiuliu This was resolved in here [#24 (comment)](https://github.com/IgorAherne/trellis-stable-projectorz/issues/24#issuecomment-2593845555)

**Comment by Sentrahara** [comment]
same problems, same troble shooting steps, finally fixed it with your ticket
太牛了我的哥

> 感谢 [#24](https://github.com/IgorAherne/trellis-stable-projectorz/issues/24) 的回答，由于我可以手动clone该项目，正好看到了install.py中相关地址，我便修改了他 文件第230行修改为 pip install "git+https://gitclone.com/github.com/EasternJournalist/utils3d.git"', 'Installing utils3d

**Comment by gerroon** [comment]
@IgorAherne 

I still have this issue with v35_py311_trellis_stableprojectorz.zip before and after "update.bat"

```

14:14:28 - INFO - Trellis API Server is starting up:
14:14:28 - INFO - Touching this window will pause it.  If it happens, click inside it and press 'Enter' to unpause

[SPARSE] Backend: spconv, Attention: xformers
Traceback (most recent call last):
  File "c:\trellis-spz\code\api_spz\main_api.py", line 107, in <module>
    from api_spz.core.state_manage import state
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\trellis-spz\code\api_spz\core\state_manage.py", line 3, in <module>
    from trellis.pipelines import TrellisImageTo3DPipeline
  File "c:\trellis-spz\code\trellis\__init__.py", line 3, in <module>
    from . import pipelines
  File "c:\trellis-spz\code\trellis\pipelines\__init__.py", line 2, in <module>
    from .trellis_image_to_3d import TrellisImageTo3DPipeline
  File "c:\trellis-spz\code\trellis\pipelines\trellis_image_to_3d.py", line 15, in <module>
    from ..representations import Gaussian, Strivec, MeshExtractResult
  File "c:\trellis-spz\code\trellis\representations\__init__.py", line 3, in <module>
    from .gaussian import Gaussian
  File "c:\trellis-spz\code\trellis\representations\gaussian\__init__.py", line 1, in <module>
    from .gaussian_model import Gaussian
  File "c:\trellis-spz\code\trellis\representations\gaussian\gaussian_model.py", line 5, in <module>
    import utils3d
ModuleNotFoundError: No module named 'utils3d'
Something went wrong, consider removing code/trellis_init_done.txt and venv folder to re-initialize from scratch
Press any key to continue . . .

```
